Travis CI can't work on Python 3.3 anymore
I know it's sad, but we have to let it go:

RuntimeError: Python 3.4 or later is required
The command "pip install coverage" failed and exited with 2 during .